import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import {
  defaultLocale,
  getLanguageOption,
  isLocale,
  LANGUAGE_COOKIE,
} from "@/i18n/config";
import { LanguageProvider } from "@/i18n/language-provider";
import { StoreProvider } from "@/redux/provider";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const cookieLocale = cookieStore.get(LANGUAGE_COOKIE)?.value;
  const locale = isLocale(cookieLocale) ? cookieLocale : defaultLocale;
  const language = getLanguageOption(locale);

  return (
    <html
      lang={locale}
      dir={language.dir}
      suppressHydrationWarning
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <StoreProvider>
          <LanguageProvider initialLocale={locale}>{children}</LanguageProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
